### PR TITLE
ILBOUDO S Charles Magloire, completed my project for AI-Enhance Web3/Blockchain Development 101 Course" at dProgramming University (dPU) to qualify for a certificate of completion" 

### PR DESCRIPTION
**Pull request by Magou226**
"I ILBOUDO S Charles Magloire, completed my project for AI-Enhance Web3/Blockchain Development 101 Course" at dProgramming University (dPU) to qualify for a certificate of completion"

### CODE REVIEW

**Review by Magou226 — COMMENTED** [review]
i make update about image

**Comment by Magou226** [comment]
ILBOUDO S Charles Magloire, completed my project for AI-Enhance Web3/Blockchain Development 101 Course" at dProgramming University (dPU) to qualify for a certificate of completion"

**Comment by SolomonFoskaay** [comment]
@Magou226 weldone but you should push this PR to your forked repo main branch nothere. So, it will be closed

**Comment by Magou226** [comment]
Ok sir...im done

Le jeu. 1 févr. 2024 à 21:26, Solomon Foskaay ***@***.***> a
écrit :

**Comment by Magou226** [comment]
Sir im confuse so iwill do another one

Le jeu. 1 févr. 2024 à 21:26, Solomon Foskaay ***@***.***> a
écrit :

**Comment by Magou226** [comment]
Sir, I tried to fix it with the IA and I think i'm done now.
If any error let me know...

Le jeu. 1 févr. 2024 à 21:26, Solomon Foskaay ***@***.***> a
écrit :

**Pull request closed without merging**
